<div style="text-align: center; background-color: #ccffcc; color: #006600; padding: 20px; border-radius: 5px;">
    <h2 style="margin: 0; font-size: 13px;">Don't forget to upvote if you liked the notebook</h2>
</div>

## Introduction to pandas


Pandas is an open-source Python library that provides easy-to-use data structures and data analysis tools. It is widely used for data manipulation, data analysis, and data cleaning tasks in the field of data science and machine learning. Pandas is built on top of NumPy, another popular Python library for 
numerical computing.

Pandas is a fast,powerful,and easy to use open source data analysis and manipulation tool,built on top of the python programming language.

## Pandas Series
A pandas Series is like a column in a table. It is a 1-D array holding data of any type.
Series: A one-dimensional labeled array capable of holding data of any type.

In [1]:
import pandas as pd
import numpy as np

## Series from lists

In [2]:
# string
country = ['Germany','Itlay','Egypt','France','China']
pd.Series(country)

0    Germany
1      Itlay
2      Egypt
3     France
4      China
dtype: object

In [3]:
# integers
marks = [76,87,43,54,98]
pd.Series(marks)

0    76
1    87
2    43
3    54
4    98
dtype: int64

In [4]:
# custom index
marks = [76,87,43,54,98]
subjects = ['english','physics','chemistry','maths','IT']
pd.Series(marks,index=subjects)

english      76
physics      87
chemistry    43
maths        54
IT           98
dtype: int64

In [5]:
#setting a name
pd.Series(marks,index=subjects,name='Arun marks')

english      76
physics      87
chemistry    43
maths        54
IT           98
Name: Arun marks, dtype: int64

## Series from dict

In [6]:
marks = {
    'english':76,
    'physics':67,
    'chemistry':43,
    'maths':54,
    'IT':98
}
marks_series = pd.Series(marks)
marks_series

english      76
physics      67
chemistry    43
maths        54
IT           98
dtype: int64

## Series Attributes

In [7]:
# size
marks_series.size

5

In [8]:
#dtype
marks_series.dtype

dtype('int64')

In [9]:
# is_unique
marks_series.is_unique

True

In [10]:
#index
marks_series.index

Index(['english', 'physics', 'chemistry', 'maths', 'IT'], dtype='object')

In [11]:
#values
marks_series.values
#type(marks_series.values)

array([76, 67, 43, 54, 98])

## Series Indexing

In [12]:
# Series works on positive indexing not work on negative indexing(works only if the indexes are string)
# integer indexing
x = pd.Series([34,56,78,34,23,32,56,76,57,83])
x[0]

34

In [13]:
#slicing
x[2:5]

2    78
3    34
4    23
dtype: int64

In [14]:
#fancy indexing
x[[1,4,3,2]]

1    56
4    23
3    34
2    78
dtype: int64

## Editing series

In [15]:
# using indexing
x[0] = 89
x

0    89
1    56
2    78
3    34
4    23
5    32
6    56
7    76
8    57
9    83
dtype: int64

In [16]:
# what if an index does not exist
marks_series['sst'] = 91
marks_series

english      76
physics      67
chemistry    43
maths        54
IT           98
sst          91
dtype: int64

In [17]:
# slicing
marks_series[2:4] = [50,51]
marks_series

english      76
physics      67
chemistry    50
maths        51
IT           98
sst          91
dtype: int64

In [18]:
# fancy indexing
marks_series[[0,3,4]] = [0,0,0]
marks_series

english       0
physics      67
chemistry    50
maths         0
IT            0
sst          91
dtype: int64

In [19]:
# Arthmetic operators
100 - marks_series

english      100
physics       33
chemistry     50
maths        100
IT           100
sst            9
dtype: int64

In [20]:
#relational operators
x >= 50

0     True
1     True
2     True
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

In [21]:
# find no of 50's 
x[x >= 50].size

7

## DataFrame
Any structure that got rows and columns is called DataFrame in pandas

![](https://media.geeksforgeeks.org/wp-content/uploads/20200414224825/f115.png)

In [22]:
#using lists
students_data = [
    [100,80,10],
    [93,76,7],
    [120,97,14],
    [80,50,2]
]
pd.DataFrame(students_data,columns=['iq','marks','package'])

    iq  marks  package
0  100     80       10
1   93     76        7
2  120     97       14
3   80     50        2

In [23]:
# using dicts

students_dict = {
    'name':['Ankit','Gaurav','Sonalika','Rashmi','Shivani'],
    'iq':[100,90,120,102,98],
    'marks':[80,70,98,89,87],
    'package':[10,7,14,4,20]
}
students = pd.DataFrame(students_dict)
students.set_index('name',inplace=True)
students

           iq  marks  package
name
Ankit     100     80       10
Gaurav     90     70        7
Sonalika  120     98       14
Rashmi    102     89        4
Shivani    98     87       20

In [24]:
# using read_csv
movies = pd.read_csv('/kaggle/input/top-rated-movies/movies.csv')
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [25]:
ipl = pd.read_csv('/kaggle/input/cricket-and-coding-crack-the-challenge/training_dataset/DataSet/IPL_Matches_Result_2008_2022.csv')
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

## DataFrame Attributes and Methods

In [26]:
#shape
movies.shape
#ipl.shape

(1629, 18)

In [27]:
#dtypes
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [28]:
#index
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [29]:
# columns
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [30]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [31]:
#values
students.values

array([[100,  80,  10],
       [ 90,  70,   7],
       [120,  98,  14],
       [102,  89,   4],
       [ 98,  87,  20]])

In [32]:
ipl.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
       [335983, 'Chandigarh', '2008-04-19', ...,
        "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']",
        'MR Benson', 'SL Shastri'],
       [335982, 'Bangalore', '2008-04-18', ...,
        "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']",
        'Asad Rauf', 'RE Koertzen']], dtype=object)

In [33]:
# head and tail
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

In [34]:
ipl.tail(3)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [35]:
#sample
ipl.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
394,980977,Chandigarh,2016-05-09,2016,39,Kings XI Punjab,Royal Challengers Bangalore,"Punjab Cricket Association IS Bindra Stadium, ...",Kings XI Punjab,field,N,Royal Challengers Bangalore,Runs,1.0,NaN,SR Watson,"['HM Amla', 'M Vijay', 'WP Saha', 'DA Miller',...","['V Kohli', 'KL Rahul', 'AB de Villiers', 'SR ...",AK Chaudhary,HDPK Dharmasena
88,1254089,Abu Dhabi,2021-10-02,2021,47,Chennai Super Kings,Rajasthan Royals,"Zayed Cricket Stadium, Abu Dhabi",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,RD Gaikwad,"['RD Gaikwad', 'F du Plessis', 'SK Raina', 'MM...","['E Lewis', 'YBK Jaiswal', 'SV Samson', 'S Dub...",CB Gaffaney,VK Sharma
233,1178396,Jaipur,2019-04-07,2019,21,Rajasthan Royals,Kolkata Knight Riders,Sawai Mansingh Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,8.0,NaN,HF Gurney,"['AM Rahane', 'JC Buttler', 'SPD Smith', 'RA T...","['CA Lynn', 'SP Narine', 'RV Uthappa', 'Shubma...",AK Chaudhary,CB Gaffaney
79,1254088,Abu Dhabi,2021-10-08,2021,55,Mumbai Indians,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",Mumbai Indians,bat,N,Mumbai Indians,Runs,42.0,NaN,Ishan Kishan,"['RG Sharma', 'Ishan Kishan', 'HH Pandya', 'KA...","['JJ Roy', 'Abhishek Sharma', 'MK Pandey', 'Mo...",Tapan Sharma,VK Sharma
555,598070,Delhi,2013-05-21,2013,Qualifier 1,Chennai Super Kings,Mumbai Indians,Feroz Shah Kotla,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,48.0,NaN,MEK Hussey,"['MEK Hussey', 'M Vijay', 'SK Raina', 'MS Dhon...","['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar...",NJ Llong,RJ Tucker

In [36]:
#info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [37]:
#describe
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [38]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [39]:
#isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [40]:
# duplicated
ipl.duplicated().sum()

0

In [41]:
movies.duplicated().sum()

0

In [42]:
# rename
students.rename(columns={'marks':'percent','package':'lpa'})

           iq  percent  lpa
name
Ankit     100       80   10
Gaurav     90       70    7
Sonalika  120       98   14
Rashmi    102       89    4
Shivani    98       87   20

## Math Methods

In [43]:
# sum -> axis argument
students.sum()

iq         510
marks      424
package     55
dtype: int64

In [44]:
students.sum(axis=1)

name
Ankit       190
Gaurav      167
Sonalika    232
Rashmi      195
Shivani     205
dtype: int64

In [45]:
students.mean()

iq         102.0
marks       84.8
package     11.0
dtype: float64

In [46]:
students.min()

iq         90
marks      70
package     4
dtype: int64

In [47]:
students.max()

iq         120
marks       98
package     20
dtype: int64

In [48]:
# standard deviation
students.std()

iq         11.045361
marks      10.473777
package     6.244998
dtype: float64

In [49]:
# variance
students.var()

iq         122.0
marks      109.7
package     39.0
dtype: float64

## Selcting cols from a DataFrame

In [50]:
# single_cols
type(movies['title_x'])

pandas.core.series.Series

In [51]:
ipl['Venue']

0                Narendra Modi Stadium, Ahmedabad
1                Narendra Modi Stadium, Ahmedabad
2                           Eden Gardens, Kolkata
3                           Eden Gardens, Kolkata
4                        Wankhede Stadium, Mumbai
                          ...
945                                  Eden Gardens
946                              Wankhede Stadium
947                              Feroz Shah Kotla
948    Punjab Cricket Association Stadium, Mohali
949                         M Chinnaswamy Stadium
Name: Venue, Length: 950, dtype: object

In [52]:
# slicing   # multiple cols
movies[['title_x','year_of_release','actors']]

,title_x,year_of_release,actors
0,Uri: The Surgical Strike,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,2019,Gippy Grewal|Zareen Khan|
1628,Humsafar,2011,Fawad Khan|

In [53]:
ipl[['Team1','Team2','WinningTeam']]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

## Selecting rows from a DataFrame
* iloc-searches using index positions
* loc-searches using index labels

In [54]:
#single row
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [55]:
# multiple rows
movies.iloc[5:16:2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,0,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,NaN,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,NaN,25 January 2019 (India)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
13,Total Dhamaal,tt7639372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Total_Dhamaal,Total Dhamaal,Total Dhamaal,0,2019,130,Action|Adventure|Comedy,4.3,4817,Total Dhamaal is the third instalment in the D...,A group of people learn about a hidden treasur...,The Wildest Adventure Ever,Ajay Devgn|Madhuri Dixit|Anil Kapoor|Riteish D...,NaN,22 February 2019 (India)
15,Badla (2019 film),tt8130968,https://upload.wikimedia.org/wikipedia/en/0/0c...,https://en.wikipedia.org/wiki/Badla_(2019_film),Badla,Badla,0,2019,118,Crime|Drama|Mystery,7.9,15499,Naina Sethi a successful entrepreneur finds he...,A dynamic young entrepreneur finds herself loc...,NaN,Amitabh Bachchan|Taapsee Pannu|Amrita Singh|An...,1 win,8 March 2019 (India)

In [56]:
# fancy indexing
movies.iloc[[0,4,5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [57]:
# loc
students

           iq  marks  package
name
Ankit     100     80       10
Gaurav     90     70        7
Sonalika  120     98       14
Rashmi    102     89        4
Shivani    98     87       20

In [58]:
students.loc['Gaurav']

iq         90
marks      70
package     7
Name: Gaurav, dtype: int64

In [59]:
#slicing
students.loc['Ankit':'Sonalika']

           iq  marks  package
name
Ankit     100     80       10
Gaurav     90     70        7
Sonalika  120     98       14

In [60]:
#fancy indexing
students.loc[['Ankit','Shivani','Rashmi']]

          iq  marks  package
name
Ankit    100     80       10
Shivani   98     87       20
Rashmi   102     89        4

In [61]:
students.iloc[:4]

           iq  marks  package
name
Ankit     100     80       10
Gaurav     90     70        7
Sonalika  120     98       14
Rashmi    102     89        4

In [62]:
# Selecting both rows and columns
movies.iloc[0:4,0:4]

,title_x,imdb_id,poster_path,wiki_link
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India

## Filtering a DataFrame

In [63]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [64]:
# find all the final winners
new_df = ipl[ipl['MatchNumber'] == 'Final']
new_df[['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [65]:
#another method
ipl[ipl['MatchNumber'] == 'Final'][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [66]:
# how many super over  finishes have occured
ipl[ipl['SuperOver'] == 'Y'].shape

(14, 20)

In [67]:
# how many matches has csk won in kolkata
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [68]:
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')].shape[0]

5

In [69]:
# toss winner is match winner in percentage
(ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]/ipl.shape[0])*100

51.473684210526315

In [70]:
# movies with rating higher than 8 and votes>10000
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] > 10000)].shape[0]

43

In [71]:
# Action movies with rating higher than 7.5
A = movies['genres'].str.split('|').apply(lambda x:'Action' in x)
# second method  A = movies['genres'].str.contains('Action')
B = movies['imdb_rating'] > 7.5
movies[A & B].shape[0]

33

In [72]:
# write a function that can return the track record of 2 teams against each other
def get_team_track_record(team1, team2, ipl):
    matches = ipl[((ipl['Team1'] == team1) & (ipl['Team2'] == team2)) |
                      ((ipl['Team1'] == team2) & (ipl['Team2'] == team1))]
    team1_wins = (matches['WinningTeam'] == team1).sum()
    team2_wins = (matches['WinningTeam'] == team2).sum()
    total_matches = len(matches)
    
    return {
        f"{team1} wins": team1_wins,
        f"{team2} wins": team2_wins,
        "Total matches": total_matches
    }

# Example usage
team1 = "Mumbai Indians"
team2 = "Chennai Super Kings"
track_record = get_team_track_record(team1, team2, ipl)
print(track_record)

{'Mumbai Indians wins': 20, 'Chennai Super Kings wins': 14, 'Total matches': 34}

## Adding new columns

In [73]:
# completely row
movies['Country'] = 'India'
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India

In [74]:
# from existing ones
movies.dropna(inplace=True)

In [75]:
movies['lead actor'] = movies['actors'].str.split('|').apply(lambda x:x[0])
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country,lead actor
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),India,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),India,Gavie Chahal
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA),India,Ayushmann Khurrana
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA),India,Sidharth Malhotra
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India),India,Ajay Devgn

# Important DataFrame Functions

In [76]:
#astype
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [77]:
ipl['ID'] = ipl['ID'].astype('int32')

In [78]:
ipl['Season'] = ipl['Season'].astype('category')

## On Iris Dataset

In [79]:
list = [10, 20, 30, 40, 50]
labels = ['A', 'B', 'C', 'D', 'E']
arr = np.array([10,20,30,40,50])
dic = {'A':10,'B':20,'C':30, 'D':40, "E":50}

In [80]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [81]:
pd.Series(data=list,index=labels) #the labels can be changed

#Also, writing "data=" and "index=" is not neccessary as they are first 2 arguments by default
pd.Series(list, labels)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [82]:
pd.Series(arr, labels) #doing the same with numpy arrays

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [83]:
#We can do all arithmetic operations on Series
ser1 = pd.Series(arr, labels)
ser2 = pd.Series(dic)

ser1 + ser2

A     20
B     40
C     60
D     80
E    100
dtype: int64

DataFrame: A two-dimensional labeled data structure, similar to a spreadsheet or SQL table, with columns of potentially different data types.

In [84]:
dict1 = {
    "name":['harry','rohan','sahil','shubh'],
    "marks":[92,54,65,19],
    "city":['rampur','kolkata','barielly','delhi']
}

In [85]:
df = pd.DataFrame(dict1)

In [86]:
df

    name  marks      city
0  harry     92    rampur
1  rohan     54   kolkata
2  sahil     65  barielly
3  shubh     19     delhi

In [87]:
df.to_csv('friends.csv')

In [88]:
df.describe()

          marks
count   4.00000
mean   57.50000
std    30.22692
min    19.00000
25%    45.25000
50%    59.50000
75%    71.75000
max    92.00000

In [89]:
df.head(2)

    name  marks     city
0  harry     92   rampur
1  rohan     54  kolkata

In [90]:
df.tail(2)

    name  marks      city
2  sahil     65  barielly
3  shubh     19     delhi

In [91]:
df.index=[1,2,3,4]

In [92]:
df

    name  marks      city
1  harry     92    rampur
2  rohan     54   kolkata
3  sahil     65  barielly
4  shubh     19     delhi

In [93]:
newdf=pd.DataFrame(np.random.rand(335,5),index=np.arange(335))

In [94]:
newdf

            0         1         2         3         4
0    0.808459  0.160640  0.671703  0.785108  0.537942
1    0.340306  0.112534  0.147191  0.692120  0.607963
2    0.440982  0.760497  0.270407  0.361180  0.288489
3    0.976025  0.768117  0.763751  0.691204  0.129106
4    0.219677  0.216576  0.222320  0.221747  0.623416
..        ...       ...       ...       ...       ...
330  0.977464  0.805342  0.594713  0.953063  0.502820
331  0.422632  0.613930  0.292802  0.464890  0.716618
332  0.693242  0.933457  0.680128  0.791997  0.083959
333  0.529999  0.995086  0.552673  0.752391  0.913634
334  0.277797  0.469296  0.512788  0.430826  0.939290

[335 rows x 5 columns]

In [95]:
newdf.head()

          0         1         2         3         4
0  0.808459  0.160640  0.671703  0.785108  0.537942
1  0.340306  0.112534  0.147191  0.692120  0.607963
2  0.440982  0.760497  0.270407  0.361180  0.288489
3  0.976025  0.768117  0.763751  0.691204  0.129106
4  0.219677  0.216576  0.222320  0.221747  0.623416

In [96]:
newdf.tail()

            0         1         2         3         4
330  0.977464  0.805342  0.594713  0.953063  0.502820
331  0.422632  0.613930  0.292802  0.464890  0.716618
332  0.693242  0.933457  0.680128  0.791997  0.083959
333  0.529999  0.995086  0.552673  0.752391  0.913634
334  0.277797  0.469296  0.512788  0.430826  0.939290

In [97]:
type(newdf)

pandas.core.frame.DataFrame

## Data Alignment 
Pandas aligns data automatically based on row and column labels, making it easy to perform operations on different datasets.

In [98]:
import pandas as pd

series1 = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
series2 = pd.Series([100, 200, 300], index=['B', 'C', 'D'])

# Performing addition on two Series with different indices
result = series1 + series2
print(result)

A      NaN
B    120.0
C    230.0
D      NaN
dtype: float64

## Missing Data Handling
Pandas handles missing data efficiently and provides methods to fill, drop, or interpolate missing values

In [99]:
import pandas as pd

data = {
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8],
}
df = pd.DataFrame(data)

In [100]:
# Checking for missing values
print(df.isnull())

       A      B
0  False  False
1  False   True
2   True  False
3  False  False

In [101]:
# Filling missing values with a specific value
filled_df = df.fillna(0)
print(filled_df)

     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  7.0
3  4.0  8.0

In [102]:
# Dropping rows with missing values
dropped_df = df.dropna()
print(dropped_df)

     A    B
0  1.0  5.0
3  4.0  8.0

## Data Input/Output
Pandas supports reading and writing data in various file formats, including CSV, Excel, SQL databases, and more

In [103]:
# Reading data from a CSV file

import pandas as pd

# Assuming 'iris.csv' is in a subdirectory named 'iris_data' within the 'input' directory
df = pd.read_csv('/kaggle/input/irisraw/irisraw.csv')

In [104]:
df

     sepal length  sepal width  petal length  petal width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [105]:
df['sepal length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length, Length: 150, dtype: float64

In [106]:
df.sort_index(axis=0,ascending=False)

     sepal length  sepal width  petal length  petal width         species
149           5.9          3.0           5.1          1.8  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
4             5.0          3.6           1.4          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
0             5.1          3.5           1.4          0.2     Iris-setosa

[150 rows x 5 columns]

In [107]:
df.sort_index(axis=1,ascending=False)

            species  sepal width  sepal length  petal width  petal length
0       Iris-setosa          3.5           5.1          0.2           1.4
1       Iris-setosa          3.0           4.9          0.2           1.4
2       Iris-setosa          3.2           4.7          0.2           1.3
3       Iris-setosa          3.1           4.6          0.2           1.5
4       Iris-setosa          3.6           5.0          0.2           1.4
..              ...          ...           ...          ...           ...
145  Iris-virginica          3.0           6.7          2.3           5.2
146  Iris-virginica          2.5           6.3          1.9           5.0
147  Iris-virginica          3.0           6.5          2.0           5.2
148  Iris-virginica          3.4           6.2          2.3           5.4
149  Iris-virginica          3.0           5.9          1.8           5.1

[150 rows x 5 columns]

In [108]:
newdf.loc[0,0]=654

In [109]:
newdf.head()

            0         1         2         3         4
0  654.000000  0.160640  0.671703  0.785108  0.537942
1    0.340306  0.112534  0.147191  0.692120  0.607963
2    0.440982  0.760497  0.270407  0.361180  0.288489
3    0.976025  0.768117  0.763751  0.691204  0.129106
4    0.219677  0.216576  0.222320  0.221747  0.623416

In [110]:
newdf.loc[0,0]=654
newdf.head(2)

            0         1         2         3         4
0  654.000000  0.160640  0.671703  0.785108  0.537942
1    0.340306  0.112534  0.147191  0.692120  0.607963

In [111]:
newdf.loc[0,'A']=65445
newdf.head(3)

            0         1         2         3         4        A
0  654.000000  0.160640  0.671703  0.785108  0.537942  65445.0
1    0.340306  0.112534  0.147191  0.692120  0.607963      NaN
2    0.440982  0.760497  0.270407  0.361180  0.288489      NaN

In [112]:
newdf.drop(0,axis=1)
#remove column

            1         2         3         4        A
0    0.160640  0.671703  0.785108  0.537942  65445.0
1    0.112534  0.147191  0.692120  0.607963      NaN
2    0.760497  0.270407  0.361180  0.288489      NaN
3    0.768117  0.763751  0.691204  0.129106      NaN
4    0.216576  0.222320  0.221747  0.623416      NaN
..        ...       ...       ...       ...      ...
330  0.805342  0.594713  0.953063  0.502820      NaN
331  0.613930  0.292802  0.464890  0.716618      NaN
332  0.933457  0.680128  0.791997  0.083959      NaN
333  0.995086  0.552673  0.752391  0.913634      NaN
334  0.469296  0.512788  0.430826  0.939290      NaN

[335 rows x 5 columns]

In [113]:
newdf.drop(0,axis=0)
#remove row

            0         1         2         3         4   A
1    0.340306  0.112534  0.147191  0.692120  0.607963 NaN
2    0.440982  0.760497  0.270407  0.361180  0.288489 NaN
3    0.976025  0.768117  0.763751  0.691204  0.129106 NaN
4    0.219677  0.216576  0.222320  0.221747  0.623416 NaN
5    0.651145  0.041177  0.712820  0.144022  0.537203 NaN
..        ...       ...       ...       ...       ...  ..
330  0.977464  0.805342  0.594713  0.953063  0.502820 NaN
331  0.422632  0.613930  0.292802  0.464890  0.716618 NaN
332  0.693242  0.933457  0.680128  0.791997  0.083959 NaN
333  0.529999  0.995086  0.552673  0.752391  0.913634 NaN
334  0.277797  0.469296  0.512788  0.430826  0.939290 NaN

[334 rows x 6 columns]

In [114]:
newdf=newdf.drop(0,axis=1)

In [115]:
newdf

            1         2         3         4        A
0    0.160640  0.671703  0.785108  0.537942  65445.0
1    0.112534  0.147191  0.692120  0.607963      NaN
2    0.760497  0.270407  0.361180  0.288489      NaN
3    0.768117  0.763751  0.691204  0.129106      NaN
4    0.216576  0.222320  0.221747  0.623416      NaN
..        ...       ...       ...       ...      ...
330  0.805342  0.594713  0.953063  0.502820      NaN
331  0.613930  0.292802  0.464890  0.716618      NaN
332  0.933457  0.680128  0.791997  0.083959      NaN
333  0.995086  0.552673  0.752391  0.913634      NaN
334  0.469296  0.512788  0.430826  0.939290      NaN

[335 rows x 5 columns]

In [116]:
df.loc[[1,2],['sepal length','petal length']]

   sepal length  petal length
1           4.9           1.4
2           4.7           1.3

In [117]:
df.loc[[1,2],:]

   sepal length  sepal width  petal length  petal width      species
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa

In [118]:
df.loc[:,['sepal length','petal length']]

     sepal length  petal length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [119]:
df.iloc[0,4]
#this is used to find any data without knowing its location name ,just by location

'Iris-setosa'

In [120]:
df.iloc[[0,4],[3,4]]

   petal width      species
0          0.2  Iris-setosa
4          0.2  Iris-setosa

In [121]:
df.loc[:,['sepal length']] #this is type of dataframe

     sepal length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [122]:
df.loc[:,('sepal length','petal length')]# this is a type of dataframe because more than one column is present

     sepal length  petal length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [123]:
data = {
    "name":['harry','rohan','sahil','shubh','karan','sona'],
    "marks":[11,12,13,14,15,16],
    "city":['rampur','kolkata','barielly','delhi','jaipur','jodhpur']
}

In [124]:
import pandas as pd

In [125]:
df3=pd.DataFrame(data)

In [126]:
df3

    name  marks      city
0  harry     11    rampur
1  rohan     12   kolkata
2  sahil     13  barielly
3  shubh     14     delhi
4  karan     15    jaipur
5   sona     16   jodhpur

In [127]:
marks=df3.loc[:,["marks"]]

In [128]:
marks

   marks
0     11
1     12
2     13
3     14
4     15
5     16

In [129]:
#df4.reset_index(inplace = True)

In [130]:
marks

   marks
0     11
1     12
2     13
3     14
4     15
5     16

In [131]:
df4=marks>14

In [132]:
df4

   marks
0  False
1  False
2  False
3  False
4   True
5   True